name: Refresh Data

on:
  schedule:
    - cron: '0 8 * * *'  # Runs daily at 17:00 KST (08:00 UTC)
  workflow_dispatch:     # Allows manual trigger from GitHub UI

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.12'

    - name: Install dependencies
      run: |
        pip install pandas
        pip install git+https://github.com/FinanceData/FinanceDataReader.git

    - name: Run refresh.py
      run: python refresh.py

    - name: Commit updated CSV
      run: |
        git config --global user.name "github-actions"
        git config --global user.email "github-actions@github.com"
        git add latest_kospi_kosdaq.csv
        git commit -m "Auto-update data: $(date +'%Y-%m-%d %H:%M:%S')" || echo "No changes to commit"
        git push
