name: Auto-refresh KRX data

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'  # Runs daily at midnight KST

permissions:
  contents: write  # Allows pushing changes using GITHUB_TOKEN

jobs:
  refresh:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run refresh.py
        run: python refresh.py

      - name: Commit and push updated CSV
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add latest_kospi_kosdaq.csv
          git commit -m "Auto-refresh full KRX data"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
